// 大学英语六级及以上词汇库（示例：部分高频词汇）
// 实际应用中这个列表应该更完整
export interface VocabularyItem {
  word: string;
  translation: string;
  level: 'CET6' | 'CET6+' | 'IELTS' | 'TOEFL';
}

// 六级及以上高频词汇库（按字母排序）
export const advancedVocabulary: Record<string, VocabularyItem> = {
  // A
  'abandon': { word: 'abandon', translation: '放弃；抛弃', level: 'CET6' },
  'abbreviate': { word: 'abbreviate', translation: '缩写；缩短', level: 'CET6' },
  'absorb': { word: 'absorb', translation: '吸收；理解', level: 'CET6' },
  'abstract': { word: 'abstract', translation: '抽象的；摘要', level: 'CET6' },
  'abundant': { word: 'abundant', translation: '丰富的；充裕的', level: 'CET6' },
  'accelerate': { word: 'accelerate', translation: '加速；促进', level: 'CET6' },
  'accommodate': { word: 'accommodate', translation: '容纳；适应', level: 'CET6' },
  'accompany': { word: 'accompany', translation: '陪伴；伴随', level: 'CET6' },
  'accomplish': { word: 'accomplish', translation: '完成；实现', level: 'CET6' },
  'accumulate': { word: 'accumulate', translation: '积累；堆积', level: 'CET6' },
  'accurate': { word: 'accurate', translation: '准确的；精确的', level: 'CET6' },
  'acknowledge': { word: 'acknowledge', translation: '承认；答谢', level: 'CET6' },
  'acquire': { word: 'acquire', translation: '获得；学到', level: 'CET6' },
  'adapt': { word: 'adapt', translation: '适应；改编', level: 'CET6' },
  'adequate': { word: 'adequate', translation: '充足的；适当的', level: 'CET6' },
  'adjacent': { word: 'adjacent', translation: '邻近的；毗连的', level: 'CET6' },
  'adjust': { word: 'adjust', translation: '调整；适应', level: 'CET6' },
  'administration': { word: 'administration', translation: '管理；行政', level: 'CET6' },
  'adolescent': { word: 'adolescent', translation: '青少年', level: 'CET6' },
  'advocate': { word: 'advocate', translation: '提倡；拥护', level: 'CET6' },
  'aesthetic': { word: 'aesthetic', translation: '美学的；审美的', level: 'CET6+' },
  'affiliate': { word: 'affiliate', translation: '使隶属；加入', level: 'CET6+' },
  'affirm': { word: 'affirm', translation: '断言；确认', level: 'CET6' },
  'aggregate': { word: 'aggregate', translation: '总计；集合', level: 'CET6+' },
  'agony': { word: 'agony', translation: '极大痛苦', level: 'CET6' },
  'albeit': { word: 'albeit', translation: '尽管；虽然', level: 'CET6+' },
  'allocate': { word: 'allocate', translation: '分配；拨出', level: 'CET6' },
  'alternate': { word: 'alternate', translation: '交替；轮流', level: 'CET6' },
  'ambiguous': { word: 'ambiguous', translation: '模糊的；含糊的', level: 'CET6' },
  'ambitious': { word: 'ambitious', translation: '有雄心的；野心勃勃的', level: 'CET6' },
  'amend': { word: 'amend', translation: '修改；改进', level: 'CET6' },
  'analogy': { word: 'analogy', translation: '类比；类推', level: 'CET6' },
  'anonymous': { word: 'anonymous', translation: '匿名的；无名的', level: 'CET6' },
  'anticipate': { word: 'anticipate', translation: '预期；期望', level: 'CET6' },
  'apparatus': { word: 'apparatus', translation: '装置；器械', level: 'CET6' },
  'apparent': { word: 'apparent', translation: '显而易见的', level: 'CET6' },
  'appealing': { word: 'appealing', translation: '吸引人的', level: 'CET6' },
  'appetite': { word: 'appetite', translation: '食欲；欲望', level: 'CET6' },
  'applaud': { word: 'applaud', translation: '鼓掌；赞同', level: 'CET6' },
  'appraisal': { word: 'appraisal', translation: '评价；估计', level: 'CET6' },
  'appreciate': { word: 'appreciate', translation: '欣赏；感激', level: 'CET6' },
  'apprentice': { word: 'apprentice', translation: '学徒；新手', level: 'CET6' },
  'appropriate': { word: 'appropriate', translation: '适当的；恰当的', level: 'CET6' },
  'arbitrary': { word: 'arbitrary', translation: '任意的；专断的', level: 'CET6+' },
  'archaeology': { word: 'archaeology', translation: '考古学', level: 'CET6' },
  'architecture': { word: 'architecture', translation: '建筑学；建筑风格', level: 'CET6' },
  'artificial': { word: 'artificial', translation: '人工的；人造的', level: 'CET6' },
  'aspire': { word: 'aspire', translation: '渴望；立志', level: 'CET6' },
  'assault': { word: 'assault', translation: '攻击；袭击', level: 'CET6' },
  'assemble': { word: 'assemble', translation: '集合；装配', level: 'CET6' },
  'assert': { word: 'assert', translation: '断言；主张', level: 'CET6' },
  'assess': { word: 'assess', translation: '评估；评定', level: 'CET6' },
  'assign': { word: 'assign', translation: '分配；指派', level: 'CET6' },
  'assimilate': { word: 'assimilate', translation: '吸收；同化', level: 'CET6+' },
  'astonish': { word: 'astonish', translation: '使惊讶', level: 'CET6' },
  'astronomy': { word: 'astronomy', translation: '天文学', level: 'CET6' },
  'atmosphere': { word: 'atmosphere', translation: '大气；气氛', level: 'CET6' },
  'attach': { word: 'attach', translation: '附上；系上', level: 'CET6' },
  'attain': { word: 'attain', translation: '达到；获得', level: 'CET6' },
  'attribute': { word: 'attribute', translation: '归因于；属性', level: 'CET6' },
  'authentic': { word: 'authentic', translation: '真实的；可信的', level: 'CET6' },
  'authorize': { word: 'authorize', translation: '授权；批准', level: 'CET6' },
  'automatic': { word: 'automatic', translation: '自动的', level: 'CET6' },
  'auxiliary': { word: 'auxiliary', translation: '辅助的；附加的', level: 'CET6+' },
  'available': { word: 'available', translation: '可获得的；有空的', level: 'CET6' },
  
  // B
  'bacteria': { word: 'bacteria', translation: '细菌', level: 'CET6' },
  'barrier': { word: 'barrier', translation: '障碍；屏障', level: 'CET6' },
  'behalf': { word: 'behalf', translation: '代表；利益', level: 'CET6' },
  'beneficial': { word: 'beneficial', translation: '有益的', level: 'CET6' },
  'biography': { word: 'biography', translation: '传记', level: 'CET6' },
  'biodiversity': { word: 'biodiversity', translation: '生物多样性', level: 'CET6+' },
  'breakthrough': { word: 'breakthrough', translation: '突破', level: 'CET6' },
  'bureaucracy': { word: 'bureaucracy', translation: '官僚主义', level: 'CET6+' },

  // C
  'capacity': { word: 'capacity', translation: '能力；容量', level: 'CET6' },
  'capitalism': { word: 'capitalism', translation: '资本主义', level: 'CET6' },
  'catastrophe': { word: 'catastrophe', translation: '灾难', level: 'CET6' },
  'category': { word: 'category', translation: '类别；范畴', level: 'CET6' },
  'cease': { word: 'cease', translation: '停止；终止', level: 'CET6' },
  'ceremony': { word: 'ceremony', translation: '典礼；仪式', level: 'CET6' },
  'certify': { word: 'certify', translation: '证明；保证', level: 'CET6' },
  'challenge': { word: 'challenge', translation: '挑战', level: 'CET6' },
  'characterize': { word: 'characterize', translation: '描述...的特征', level: 'CET6' },
  'circumstance': { word: 'circumstance', translation: '环境；情况', level: 'CET6' },
  'cite': { word: 'cite', translation: '引用；引证', level: 'CET6' },
  'civilization': { word: 'civilization', translation: '文明', level: 'CET6' },
  'clarify': { word: 'clarify', translation: '阐明；澄清', level: 'CET6' },
  'classical': { word: 'classical', translation: '古典的；经典的', level: 'CET6' },
  'classify': { word: 'classify', translation: '分类；归类', level: 'CET6' },
  'coherent': { word: 'coherent', translation: '连贯的；一致的', level: 'CET6+' },
  'coincide': { word: 'coincide', translation: '同时发生；一致', level: 'CET6' },
  'collaborate': { word: 'collaborate', translation: '合作；协作', level: 'CET6' },
  'collapse': { word: 'collapse', translation: '倒塌；崩溃', level: 'CET6' },
  'colleague': { word: 'colleague', translation: '同事', level: 'CET6' },
  'collective': { word: 'collective', translation: '集体的；共同的', level: 'CET6' },
  'colony': { word: 'colony', translation: '殖民地', level: 'CET6' },
  'commence': { word: 'commence', translation: '开始；着手', level: 'CET6' },
  'commission': { word: 'commission', translation: '委员会；佣金', level: 'CET6' },
  'commitment': { word: 'commitment', translation: '承诺；投入', level: 'CET6' },
  'commodity': { word: 'commodity', translation: '商品', level: 'CET6' },
  'commonwealth': { word: 'commonwealth', translation: '联邦；共和国', level: 'CET6+' },
  'compatible': { word: 'compatible', translation: '兼容的；和谐的', level: 'CET6' },
  'compensate': { word: 'compensate', translation: '补偿；赔偿', level: 'CET6' },
  'competent': { word: 'competent', translation: '有能力的；胜任的', level: 'CET6' },
  'compile': { word: 'compile', translation: '编译；汇编', level: 'CET6' },
  'complement': { word: 'complement', translation: '补充；补足', level: 'CET6' },
  'complexity': { word: 'complexity', translation: '复杂性', level: 'CET6' },
  'compliance': { word: 'compliance', translation: '遵守；服从', level: 'CET6' },
  'component': { word: 'component', translation: '组成部分；成分', level: 'CET6' },
  'compose': { word: 'compose', translation: '组成；创作', level: 'CET6' },
  'compound': { word: 'compound', translation: '化合物；复合的', level: 'CET6' },
  'comprehensive': { word: 'comprehensive', translation: '综合的；全面的', level: 'CET6' },
  'compromise': { word: 'compromise', translation: '妥协；折衷', level: 'CET6' },
  'compulsory': { word: 'compulsory', translation: '强制的；义务的', level: 'CET6' },
  'conceive': { word: 'conceive', translation: '构思；怀孕', level: 'CET6' },
  'concentrate': { word: 'concentrate', translation: '集中；专心', level: 'CET6' },
  'concept': { word: 'concept', translation: '概念；观念', level: 'CET6' },
  'concise': { word: 'concise', translation: '简明的；简洁的', level: 'CET6' },
  'conclude': { word: 'conclude', translation: '结束；推断', level: 'CET6' },
  'concrete': { word: 'concrete', translation: '具体的；混凝土', level: 'CET6' },
  'condemn': { word: 'condemn', translation: '谴责；判刑', level: 'CET6' },
  'conduct': { word: 'conduct', translation: '进行；行为', level: 'CET6' },
  'confer': { word: 'confer', translation: '授予；商讨', level: 'CET6' },
  'conference': { word: 'conference', translation: '会议', level: 'CET6' },
  'confess': { word: 'confess', translation: '承认；坦白', level: 'CET6' },
  'configuration': { word: 'configuration', translation: '配置；结构', level: 'CET6+' },
  'confine': { word: 'confine', translation: '限制；禁闭', level: 'CET6' },
  'confirm': { word: 'confirm', translation: '确认；证实', level: 'CET6' },
  'conflict': { word: 'conflict', translation: '冲突；矛盾', level: 'CET6' },
  'conform': { word: 'conform', translation: '遵守；符合', level: 'CET6' },
  'confront': { word: 'confront', translation: '面对；对抗', level: 'CET6' },
  'congress': { word: 'congress', translation: '国会；代表大会', level: 'CET6' },
  'conscience': { word: 'conscience', translation: '良心；道德心', level: 'CET6' },
  'conscious': { word: 'conscious', translation: '有意识的；自觉的', level: 'CET6' },
  'consecutive': { word: 'consecutive', translation: '连续的', level: 'CET6' },
  'consensus': { word: 'consensus', translation: '共识；一致意见', level: 'CET6' },
  'consent': { word: 'consent', translation: '同意；准许', level: 'CET6' },
  'consequence': { word: 'consequence', translation: '结果；后果', level: 'CET6' },
  'conservation': { word: 'conservation', translation: '保护；保存', level: 'CET6' },
  'conservative': { word: 'conservative', translation: '保守的', level: 'CET6' },
  'considerable': { word: 'considerable', translation: '相当大的', level: 'CET6' },
  'considerate': { word: 'considerate', translation: '体贴的;考虑周到的', level: 'CET6' },
  'consistent': { word: 'consistent', translation: '一致的；连续的', level: 'CET6' },
  'consolidate': { word: 'consolidate', translation: '巩固;合并', level: 'CET6' },
  'conspiracy': { word: 'conspiracy', translation: '阴谋;密谋', level: 'CET6' },
  'constant': { word: 'constant', translation: '不断的;恒定的', level: 'CET6' },
  'constitute': { word: 'constitute', translation: '构成;组成', level: 'CET6' },
  'constitution': { word: 'constitution', translation: '宪法;体质', level: 'CET6' },
  'constrain': { word: 'constrain', translation: '限制;约束', level: 'CET6' },
  'construct': { word: 'construct', translation: '建造;构筑', level: 'CET6' },
  'consult': { word: 'consult', translation: '咨询;请教', level: 'CET6' },
  'consume': { word: 'consume', translation: '消耗;消费', level: 'CET6' },
  'contemplate': { word: 'contemplate', translation: '沉思;打算', level: 'CET6' },
  'contemporary': { word: 'contemporary', translation: '当代的;同时代的', level: 'CET6' },
  'contempt': { word: 'contempt', translation: '轻视;藐视', level: 'CET6' },
  'contest': { word: 'contest', translation: '竞赛;争论', level: 'CET6' },
  'context': { word: 'context', translation: '上下文;背景', level: 'CET6' },
  'continent': { word: 'continent', translation: '大陆;洲', level: 'CET6' },
  'continual': { word: 'continual', translation: '频繁的;持续的', level: 'CET6' },
  'contradict': { word: 'contradict', translation: '反驳;矛盾', level: 'CET6' },
  'contrary': { word: 'contrary', translation: '相反的', level: 'CET6' },
  'contrast': { word: 'contrast', translation: '对比;对照', level: 'CET6' },
  'contribute': { word: 'contribute', translation: '贡献;捐献', level: 'CET6' },
  'controversy': { word: 'controversy', translation: '争论;辩论', level: 'CET6' },
  'convenient': { word: 'convenient', translation: '方便的', level: 'CET6' },
  'convention': { word: 'convention', translation: '大会;惯例', level: 'CET6' },
  'conventional': { word: 'conventional', translation: '传统的;常规的', level: 'CET6' },
  'converse': { word: 'converse', translation: '交谈;相反的', level: 'CET6' },
  'convert': { word: 'convert', translation: '转换;改变', level: 'CET6' },
  'convey': { word: 'convey', translation: '传达;运送', level: 'CET6' },
  'convict': { word: 'convict', translation: '证明...有罪', level: 'CET6' },
  'convince': { word: 'convince', translation: '使信服;说服', level: 'CET6' },
  'cooperate': { word: 'cooperate', translation: '合作;配合', level: 'CET6' },
  'coordinate': { word: 'coordinate', translation: '协调;坐标', level: 'CET6' },
  'corporation': { word: 'corporation', translation: '公司;企业', level: 'CET6' },
  'correlate': { word: 'correlate', translation: '相关联;使关联', level: 'CET6+' },
  'correspond': { word: 'correspond', translation: '通信;符合', level: 'CET6' },
  'corrupt': { word: 'corrupt', translation: '腐败的;贪污的', level: 'CET6' },
  'council': { word: 'council', translation: '委员会;理事会', level: 'CET6' },
  'counsel': { word: 'counsel', translation: '劝告;律师', level: 'CET6' },
  'counterpart': { word: 'counterpart', translation: '对应的人或物', level: 'CET6' },
  'courtesy': { word: 'courtesy', translation: '礼貌;好意', level: 'CET6' },
  'creative': { word: 'creative', translation: '创造性的', level: 'CET6' },
  'credit': { word: 'credit', translation: '信用;学分', level: 'CET6' },
  'crew': { word: 'crew', translation: '全体船员;一组工作人员', level: 'CET6' },
  'crisis': { word: 'crisis', translation: '危机;紧要关头', level: 'CET6' },
  'criterion': { word: 'criterion', translation: '标准;准则', level: 'CET6' },
  'critical': { word: 'critical', translation: '批评的;关键的', level: 'CET6' },
  'crucial': { word: 'crucial', translation: '至关重要的', level: 'CET6' },
  'crude': { word: 'crude', translation: '粗糙的;天然的', level: 'CET6' },
  'cultivate': { word: 'cultivate', translation: '培养;耕作', level: 'CET6' },
  'currency': { word: 'currency', translation: '货币;通货', level: 'CET6' },
  'curriculum': { word: 'curriculum', translation: '课程', level: 'CET6' },
  'custody': { word: 'custody', translation: '监护;保管', level: 'CET6' },

  // D-Z略...（可以继续扩展）
  'debate': { word: 'debate', translation: '辩论;讨论', level: 'CET6' },
  'decade': { word: 'decade', translation: '十年', level: 'CET6' },
  'decay': { word: 'decay', translation: '腐烂;衰退', level: 'CET6' },
  'deceive': { word: 'deceive', translation: '欺骗', level: 'CET6' },
  'decent': { word: 'decent', translation: '得体的;相当好的', level: 'CET6' },
  'declaration': { word: 'declaration', translation: '宣言;声明', level: 'CET6' },
  'decline': { word: 'decline', translation: '下降;拒绝', level: 'CET6' },
  'decorate': { word: 'decorate', translation: '装饰', level: 'CET6' },
  'dedicate': { word: 'dedicate', translation: '奉献;致力于', level: 'CET6' },
  'deduce': { word: 'deduce', translation: '推论;演绎', level: 'CET6' },
  'defect': { word: 'defect', translation: '缺陷;缺点', level: 'CET6' },
  'defend': { word: 'defend', translation: '保卫;辩护', level: 'CET6' },
  'deficiency': { word: 'deficiency', translation: '缺乏;不足', level: 'CET6' },
  'define': { word: 'define', translation: '定义;解释', level: 'CET6' },
  'definite': { word: 'definite', translation: '明确的;肯定的', level: 'CET6' },
  'degenerate': { word: 'degenerate', translation: '退化;堕落', level: 'CET6+' },
  'deliberate': { word: 'deliberate', translation: '故意的;深思熟虑的', level: 'CET6' },
  'delicate': { word: 'delicate', translation: '精致的;脆弱的', level: 'CET6' },
  'democracy': { word: 'democracy', translation: '民主;民主制度', level: 'CET6' },
  'demonstrate': { word: 'demonstrate', translation: '证明;示范', level: 'CET6' },
  'deny': { word: 'deny', translation: '否认;拒绝', level: 'CET6' },
  'depart': { word: 'depart', translation: '离开;出发', level: 'CET6' },
  'deposit': { word: 'deposit', translation: '存款;沉淀', level: 'CET6' },
  'depress': { word: 'depress', translation: '使沮丧;使萧条', level: 'CET6' },
  'deprive': { word: 'deprive', translation: '剥夺', level: 'CET6' },
  'derive': { word: 'derive', translation: '得到;起源', level: 'CET6' },
  'descend': { word: 'descend', translation: '下降;遗传', level: 'CET6' },
  'designate': { word: 'designate', translation: '指定;标明', level: 'CET6' },
  'desirable': { word: 'desirable', translation: '值得拥有的', level: 'CET6' },
  'despair': { word: 'despair', translation: '绝望', level: 'CET6' },
  'desperate': { word: 'desperate', translation: '绝望的;不顾一切的', level: 'CET6' },
  'despise': { word: 'despise', translation: '鄙视;看不起', level: 'CET6' },
  'destination': { word: 'destination', translation: '目的地', level: 'CET6' },
  'destiny': { word: 'destiny', translation: '命运', level: 'CET6' },
  'detect': { word: 'detect', translation: '发现;察觉', level: 'CET6' },
  'deter': { word: 'deter', translation: '威慑;阻止', level: 'CET6' },
  'determine': { word: 'determine', translation: '决定;确定', level: 'CET6' },
  'device': { word: 'device', translation: '装置;设备', level: 'CET6' },
  'devise': { word: 'devise', translation: '设计;想出', level: 'CET6' },
  'devote': { word: 'devote', translation: '致力于;奉献', level: 'CET6' },
  'diagnose': { word: 'diagnose', translation: '诊断', level: 'CET6' },
  'dialogue': { word: 'dialogue', translation: '对话', level: 'CET6' },
  'dictate': { word: 'dictate', translation: '口述;支配', level: 'CET6' },
  'differentiate': { word: 'differentiate', translation: '区分;使不同', level: 'CET6' },
  'diffuse': { word: 'diffuse', translation: '扩散;传播', level: 'CET6+' },
  'dignity': { word: 'dignity', translation: '尊严', level: 'CET6' },
  'dilemma': { word: 'dilemma', translation: '困境;进退两难', level: 'CET6' },
  'dilute': { word: 'dilute', translation: '稀释;削弱', level: 'CET6' },
  'dimension': { word: 'dimension', translation: '维度;尺寸', level: 'CET6' },
  'diminish': { word: 'diminish', translation: '减少;降低', level: 'CET6' },
  'diplomat': { word: 'diplomat', translation: '外交官', level: 'CET6' },
  'directory': { word: 'directory', translation: '目录;名录', level: 'CET6' },
  'disability': { word: 'disability', translation: '残疾;无能', level: 'CET6' },
  'disaster': { word: 'disaster', translation: '灾难', level: 'CET6' },
  'discard': { word: 'discard', translation: '丢弃;抛弃', level: 'CET6' },
  'discipline': { word: 'discipline', translation: '纪律;学科', level: 'CET6' },
  'disclose': { word: 'disclose', translation: '揭露;透露', level: 'CET6' },
  'discourse': { word: 'discourse', translation: '演讲;论述', level: 'CET6+' },
  'discrepancy': { word: 'discrepancy', translation: '差异;不一致', level: 'CET6+' },
  'discrete': { word: 'discrete', translation: '分离的;离散的', level: 'CET6+' },
  'discriminate': { word: 'discriminate', translation: '歧视;区别', level: 'CET6' },
  'disguise': { word: 'disguise', translation: '假装;伪装', level: 'CET6' },
  'disgust': { word: 'disgust', translation: '厌恶;反感', level: 'CET6' },
  'dismiss': { word: 'dismiss', translation: '解雇;驳回', level: 'CET6' },
  'disorder': { word: 'disorder', translation: '混乱;失调', level: 'CET6' },
  'dispatch': { word: 'dispatch', translation: '派遣;发送', level: 'CET6' },
  'disperse': { word: 'disperse', translation: '分散;散开', level: 'CET6' },
  'displace': { word: 'displace', translation: '取代;使流离失所', level: 'CET6' },
  'disposable': { word: 'disposable', translation: '一次性的;可支配的', level: 'CET6' },
  'disposal': { word: 'disposal', translation: '处理;清除', level: 'CET6' },
  'dispose': { word: 'dispose', translation: '处理;布置', level: 'CET6' },
  'dispute': { word: 'dispute', translation: '争论;争议', level: 'CET6' },
  'disrupt': { word: 'disrupt', translation: '扰乱;中断', level: 'CET6' },
  'dissolve': { word: 'dissolve', translation: '溶解;解散', level: 'CET6' },
  'distinct': { word: 'distinct', translation: '明显的;独特的', level: 'CET6' },
  'distinguish': { word: 'distinguish', translation: '区分;辨别', level: 'CET6' },
  'distort': { word: 'distort', translation: '扭曲;歪曲', level: 'CET6' },
  'distribute': { word: 'distribute', translation: '分配;分发', level: 'CET6' },
  'diverse': { word: 'diverse', translation: '多样的;不同的', level: 'CET6' },
  'divert': { word: 'divert', translation: '转移;使分心', level: 'CET6' },
  'divine': { word: 'divine', translation: '神的;神圣的', level: 'CET6' },
  'documentary': { word: 'documentary', translation: '记录片;文献的', level: 'CET6' },
  'domain': { word: 'domain', translation: '领域;域', level: 'CET6' },
  'domestic': { word: 'domestic', translation: '国内的;家庭的', level: 'CET6' },
  'dominant': { word: 'dominant', translation: '占优势的;支配的', level: 'CET6' },
  'donate': { word: 'donate', translation: '捐赠', level: 'CET6' },
  'doom': { word: 'doom', translation: '厄运;注定', level: 'CET6' },
  'draft': { word: 'draft', translation: '草稿;征兵', level: 'CET6' },
  'drain': { word: 'drain', translation: '排水;消耗', level: 'CET6' },
  'dramatic': { word: 'dramatic', translation: '戏剧的;引人注目的', level: 'CET6' },
  'drastic': { word: 'drastic', translation: '激烈的;猛烈的', level: 'CET6' },
  'drawback': { word: 'drawback', translation: '缺点;障碍', level: 'CET6' },
  'dread': { word: 'dread', translation: '恐惧;担心', level: 'CET6' },
  'drought': { word: 'drought', translation: '干旱', level: 'CET6' },
  'dumb': { word: 'dumb', translation: '哑的;愚蠢的', level: 'CET6' },
  'duplicate': { word: 'duplicate', translation: '复制;副本', level: 'CET6' },
  'durable': { word: 'durable', translation: '耐用的;持久的', level: 'CET6' },
  'duration': { word: 'duration', translation: '持续时间', level: 'CET6' },
  'dwell': { word: 'dwell', translation: '居住;细想', level: 'CET6' },
  'dynamic': { word: 'dynamic', translation: '动态的;有活力的', level: 'CET6' },
  
  // E-Z继续...（根据需要扩展）
  'ecology': { word: 'ecology', translation: '生态学', level: 'CET6' },
  'economy': { word: 'economy', translation: '经济', level: 'CET6' },
  'ecosystem': { word: 'ecosystem', translation: '生态系统', level: 'CET6+' },
  'elaborate': { word: 'elaborate', translation: '精心制作的;详述', level: 'CET6' },
  'elderly': { word: 'elderly', translation: '年长的', level: 'CET6' },
  'election': { word: 'election', translation: '选举', level: 'CET6' },
  'elegant': { word: 'elegant', translation: '优雅的', level: 'CET6' },
  'element': { word: 'element', translation: '元素;要素', level: 'CET6' },
  'elementary': { word: 'elementary', translation: '基本的;初级的', level: 'CET6' },
  'elevate': { word: 'elevate', translation: '提升;举起', level: 'CET6' },
  'eliminate': { word: 'eliminate', translation: '消除;淘汰', level: 'CET6' },
  'elite': { word: 'elite', translation: '精英', level: 'CET6' },
  'eloquent': { word: 'eloquent', translation: '雄辩的;有说服力的', level: 'CET6+' },
  'embark': { word: 'embark', translation: '从事;上船', level: 'CET6' },
  'embarrass': { word: 'embarrass', translation: '使尴尬', level: 'CET6' },
  'embed': { word: 'embed', translation: '嵌入;植入', level: 'CET6' },
  'embrace': { word: 'embrace', translation: '拥抱;接受', level: 'CET6' },
  'emerge': { word: 'emerge', translation: '出现;浮现', level: 'CET6' },
  'emergency': { word: 'emergency', translation: '紧急情况', level: 'CET6' },
  'emigrate': { word: 'emigrate', translation: '移居国外', level: 'CET6' },
  'emission': { word: 'emission', translation: '排放;发射', level: 'CET6' },
  'emotion': { word: 'emotion', translation: '情感;情绪', level: 'CET6' },
  'emperor': { word: 'emperor', translation: '皇帝', level: 'CET6' },
  'emphasis': { word: 'emphasis', translation: '强调;重点', level: 'CET6' },
  'emphasize': { word: 'emphasize', translation: '强调', level: 'CET6' },
  'empire': { word: 'empire', translation: '帝国', level: 'CET6' },
  'empirical': { word: 'empirical', translation: '经验的;实证的', level: 'CET6+' },
  'employ': { word: 'employ', translation: '雇用;使用', level: 'CET6' },
  'enable': { word: 'enable', translation: '使能够', level: 'CET6' },
  'enclose': { word: 'enclose', translation: '围住;附上', level: 'CET6' },
  'encounter': { word: 'encounter', translation: '遭遇;邂逅', level: 'CET6' },
  'encourage': { word: 'encourage', translation: '鼓励', level: 'CET6' },
  'endeavor': { word: 'endeavor', translation: '努力;尽力', level: 'CET6' },
  'endorse': { word: 'endorse', translation: '认可;背书', level: 'CET6' },
  'endure': { word: 'endure', translation: '忍受;持久', level: 'CET6' },
  'enforce': { word: 'enforce', translation: '实施;强制执行', level: 'CET6' },
  'engage': { word: 'engage', translation: '从事;订婚', level: 'CET6' },
  'enhance': { word: 'enhance', translation: '提高;增强', level: 'CET6' },
  'enlighten': { word: 'enlighten', translation: '启发;启蒙', level: 'CET6' },
  'enormous': { word: 'enormous', translation: '巨大的', level: 'CET6' },
  'enrich': { word: 'enrich', translation: '使丰富', level: 'CET6' },
  'enroll': { word: 'enroll', translation: '登记;注册', level: 'CET6' },
  'ensure': { word: 'ensure', translation: '确保', level: 'CET6' },
  'entail': { word: 'entail', translation: '需要;使必要', level: 'CET6' },
  'enterprise': { word: 'enterprise', translation: '企业;事业', level: 'CET6' },
  'entertain': { word: 'entertain', translation: '娱乐;招待', level: 'CET6' },
  'enthusiasm': { word: 'enthusiasm', translation: '热情', level: 'CET6' },
  'entitle': { word: 'entitle', translation: '使有权利;给...题名', level: 'CET6' },
  'entity': { word: 'entity', translation: '实体;存在', level: 'CET6+' },
  'entrepreneur': { word: 'entrepreneur', translation: '企业家', level: 'CET6' },
  'environment': { word: 'environment', translation: '环境', level: 'CET6' },
  'envision': { word: 'envision', translation: '想象;展望', level: 'CET6' },
  'episode': { word: 'episode', translation: '一集;插曲', level: 'CET6' },
  'equation': { word: 'equation', translation: '方程式;等式', level: 'CET6' },
  'equator': { word: 'equator', translation: '赤道', level: 'CET6' },
  'equip': { word: 'equip', translation: '装备;配备', level: 'CET6' },
  'equivalent': { word: 'equivalent', translation: '相等的;等价物', level: 'CET6' },
  'era': { word: 'era', translation: '时代;纪元', level: 'CET6' },
  'erase': { word: 'erase', translation: '擦除;抹去', level: 'CET6' },
  'erect': { word: 'erect', translation: '建立;竖立', level: 'CET6' },
  'erode': { word: 'erode', translation: '侵蚀;腐蚀', level: 'CET6' },
  'erupt': { word: 'erupt', translation: '爆发;喷出', level: 'CET6' },
  'escalate': { word: 'escalate', translation: '逐步升级', level: 'CET6' },
  'escape': { word: 'escape', translation: '逃跑;逃避', level: 'CET6' },
  'escort': { word: 'escort', translation: '护送;陪同', level: 'CET6' },
  'essence': { word: 'essence', translation: '本质;精髓', level: 'CET6' },
  'essential': { word: 'essential', translation: '必要的;本质的', level: 'CET6' },
  'establish': { word: 'establish', translation: '建立;确立', level: 'CET6' },
  'estate': { word: 'estate', translation: '房地产;财产', level: 'CET6' },
  'estimate': { word: 'estimate', translation: '估计;估价', level: 'CET6' },
  'eternal': { word: 'eternal', translation: '永恒的', level: 'CET6' },
  'ethical': { word: 'ethical', translation: '伦理的;道德的', level: 'CET6' },
  'ethnic': { word: 'ethnic', translation: '民族的;种族的', level: 'CET6' },
  'evacuate': { word: 'evacuate', translation: '疏散;撤离', level: 'CET6' },
  'evaluate': { word: 'evaluate', translation: '评估;评价', level: 'CET6' },
  'evaporate': { word: 'evaporate', translation: '蒸发;消失', level: 'CET6' },
  'eventual': { word: 'eventual', translation: '最终的', level: 'CET6' },
  'evidence': { word: 'evidence', translation: '证据;证明', level: 'CET6' },
  'evident': { word: 'evident', translation: '明显的', level: 'CET6' },
  'evil': { word: 'evil', translation: '邪恶的;罪恶', level: 'CET6' },
  'evoke': { word: 'evoke', translation: '唤起;引起', level: 'CET6' },
  'evolution': { word: 'evolution', translation: '进化;演变', level: 'CET6' },
  'evolve': { word: 'evolve', translation: '进化;演变', level: 'CET6' },
  'exaggerate': { word: 'exaggerate', translation: '夸大;夸张', level: 'CET6' },
  'exceed': { word: 'exceed', translation: '超过;胜过', level: 'CET6' },
  'excel': { word: 'excel', translation: '擅长;胜过', level: 'CET6' },
  'exception': { word: 'exception', translation: '例外', level: 'CET6' },
  'excess': { word: 'excess', translation: '过量;过度', level: 'CET6' },
  'excessive': { word: 'excessive', translation: '过度的', level: 'CET6' },
  'exclaim': { word: 'exclaim', translation: '惊叫;呼喊', level: 'CET6' },
  'exclude': { word: 'exclude', translation: '排除;排斥', level: 'CET6' },
  'exclusive': { word: 'exclusive', translation: '独有的;排外的', level: 'CET6' },
  'excursion': { word: 'excursion', translation: '远足;短途旅行', level: 'CET6' },
  'execute': { word: 'execute', translation: '执行;处死', level: 'CET6' },
  'executive': { word: 'executive', translation: '执行的;主管', level: 'CET6' },
  'exempt': { word: 'exempt', translation: '豁免;免除', level: 'CET6' },
  'exert': { word: 'exert', translation: '运用;施加', level: 'CET6' },
  'exhaust': { word: 'exhaust', translation: '使筋疲力尽;用尽', level: 'CET6' },
  'exhibit': { word: 'exhibit', translation: '展览;展示', level: 'CET6' },
  'exile': { word: 'exile', translation: '流放;放逐', level: 'CET6' },
  'existence': { word: 'existence', translation: '存在;生存', level: 'CET6' },
  'exotic': { word: 'exotic', translation: '异国的;奇异的', level: 'CET6' },
  'expand': { word: 'expand', translation: '扩大;膨胀', level: 'CET6' },
  'expedition': { word: 'expedition', translation: '远征;探险', level: 'CET6' },
  'expenditure': { word: 'expenditure', translation: '支出;花费', level: 'CET6' },
  'expertise': { word: 'expertise', translation: '专门知识;专长', level: 'CET6' },
  'expire': { word: 'expire', translation: '期满;去世', level: 'CET6' },
  'explicit': { word: 'explicit', translation: '明确的;清楚的', level: 'CET6' },
  'explode': { word: 'explode', translation: '爆炸', level: 'CET6' },
  'exploit': { word: 'exploit', translation: '开发;剥削', level: 'CET6' },
  'explore': { word: 'explore', translation: '探索;探险', level: 'CET6' },
  'explosion': { word: 'explosion', translation: '爆炸', level: 'CET6' },
  'explosive': { word: 'explosive', translation: '爆炸性的;炸药', level: 'CET6' },
  'export': { word: 'export', translation: '出口;输出', level: 'CET6' },
  'expose': { word: 'expose', translation: '暴露;揭露', level: 'CET6' },
  'expressive': { word: 'expressive', translation: '表现的;富于表情的', level: 'CET6' },
  'extend': { word: 'extend', translation: '延伸;扩展', level: 'CET6' },
  'extensive': { word: 'extensive', translation: '广泛的;大量的', level: 'CET6' },
  'extent': { word: 'extent', translation: '程度;范围', level: 'CET6' },
  'exterior': { word: 'exterior', translation: '外部的;外观', level: 'CET6' },
  'external': { word: 'external', translation: '外部的;外面的', level: 'CET6' },
  'extinct': { word: 'extinct', translation: '灭绝的;绝种的', level: 'CET6' },
  'extinguish': { word: 'extinguish', translation: '熄灭;扑灭', level: 'CET6' },
  'extract': { word: 'extract', translation: '提取;摘录', level: 'CET6' },
  'extraordinary': { word: 'extraordinary', translation: '非凡的;特别的', level: 'CET6' },
  'extravagant': { word: 'extravagant', translation: '奢侈的;浪费的', level: 'CET6' },
  'extreme': { word: 'extreme', translation: '极端的;极度的', level: 'CET6' },
  
  // F
  'fabric': { word: 'fabric', translation: '织物;结构', level: 'CET6' },
  'fabricate': { word: 'fabricate', translation: '制造;捏造', level: 'CET6' },
  'facilitate': { word: 'facilitate', translation: '促进;使便利', level: 'CET6' },
  'facility': { word: 'facility', translation: '设施;设备', level: 'CET6' },
  'faculty': { word: 'faculty', translation: '全体教员;才能', level: 'CET6' },
  'fade': { word: 'fade', translation: '褪色;逐渐消失', level: 'CET6' },
  'famine': { word: 'famine', translation: '饥荒', level: 'CET6' },
  'fantasy': { word: 'fantasy', translation: '幻想;想象', level: 'CET6' },
  'fascinate': { word: 'fascinate', translation: '使着迷', level: 'CET6' },
  'fatal': { word: 'fatal', translation: '致命的;灾难性的', level: 'CET6' },
  'fatigue': { word: 'fatigue', translation: '疲劳;劳累', level: 'CET6' },
  'feasible': { word: 'feasible', translation: '可行的', level: 'CET6' },
  'feature': { word: 'feature', translation: '特征;特色', level: 'CET6' },
  'federal': { word: 'federal', translation: '联邦的', level: 'CET6' },
  'fee': { word: 'fee', translation: '费用', level: 'CET6' },
  'feedback': { word: 'feedback', translation: '反馈', level: 'CET6' },
  'feminine': { word: 'feminine', translation: '女性的;阴性的', level: 'CET6' },
  'ferry': { word: 'ferry', translation: '渡船;摆渡', level: 'CET6' },
  'fertile': { word: 'fertile', translation: '肥沃的;能生育的', level: 'CET6' },
  'festival': { word: 'festival', translation: '节日;音乐节', level: 'CET6' },
  'fiber': { word: 'fiber', translation: '纤维', level: 'CET6' },
  'fiction': { word: 'fiction', translation: '小说;虚构', level: 'CET6' },
  'fierce': { word: 'fierce', translation: '凶猛的;激烈的', level: 'CET6' },
  'finance': { word: 'finance', translation: '财政;金融', level: 'CET6' },
  'finite': { word: 'finite', translation: '有限的', level: 'CET6+' },
  'firm': { word: 'firm', translation: '公司;坚固的', level: 'CET6' },
  'fiscal': { word: 'fiscal', translation: '财政的', level: 'CET6' },
  'fission': { word: 'fission', translation: '裂变;分裂', level: 'CET6+' },
  'flap': { word: 'flap', translation: '拍打;飘动', level: 'CET6' },
  'flare': { word: 'flare', translation: '闪耀;爆发', level: 'CET6' },
  'flash': { word: 'flash', translation: '闪光;闪现', level: 'CET6' },
  'flee': { word: 'flee', translation: '逃走;逃离', level: 'CET6' },
  'fleet': { word: 'fleet', translation: '舰队;船队', level: 'CET6' },
  'flexible': { word: 'flexible', translation: '灵活的;可弯曲的', level: 'CET6' },
  'flicker': { word: 'flicker', translation: '闪烁;摇曳', level: 'CET6' },
  'flourish': { word: 'flourish', translation: '繁荣;茂盛', level: 'CET6' },
  'fluctuate': { word: 'fluctuate', translation: '波动;起伏', level: 'CET6' },
  'fluent': { word: 'fluent', translation: '流利的', level: 'CET6' },
  'fluid': { word: 'fluid', translation: '流体;液体', level: 'CET6' },
  'flush': { word: 'flush', translation: '冲洗;脸红', level: 'CET6' },
  'flutter': { word: 'flutter', translation: '飘动;振翅', level: 'CET6' },
  'foam': { word: 'foam', translation: '泡沫', level: 'CET6' },
  'folk': { word: 'folk', translation: '民间的;人们', level: 'CET6' },
  'foremost': { word: 'foremost', translation: '首要的;最重要的', level: 'CET6' },
  'forge': { word: 'forge', translation: '锻造;伪造', level: 'CET6' },
  'formal': { word: 'formal', translation: '正式的;正规的', level: 'CET6' },
  'format': { word: 'format', translation: '格式;版式', level: 'CET6' },
  'formidable': { word: 'formidable', translation: '可怕的;强大的', level: 'CET6' },
  'formula': { word: 'formula', translation: '公式;配方', level: 'CET6' },
  'formulate': { word: 'formulate', translation: '制定;阐明', level: 'CET6' },
  'forth': { word: 'forth', translation: '向前;向外', level: 'CET6' },
  'fortnight': { word: 'fortnight', translation: '两星期', level: 'CET6' },
  'fortunate': { word: 'fortunate', translation: '幸运的', level: 'CET6' },
  'forum': { word: 'forum', translation: '论坛;讨论会', level: 'CET6' },
  'fossil': { word: 'fossil', translation: '化石', level: 'CET6' },
  'foster': { word: 'foster', translation: '培养;促进', level: 'CET6' },
  'foul': { word: 'foul', translation: '污秽的;犯规', level: 'CET6' },
  'foundation': { word: 'foundation', translation: '基础;地基', level: 'CET6' },
  'fraction': { word: 'fraction', translation: '分数;片段', level: 'CET6' },
  'fracture': { word: 'fracture', translation: '骨折;破裂', level: 'CET6' },
  'fragile': { word: 'fragile', translation: '易碎的;脆弱的', level: 'CET6' },
  'fragment': { word: 'fragment', translation: '碎片;片段', level: 'CET6' },
  'framework': { word: 'framework', translation: '框架;结构', level: 'CET6' },
  'frankly': { word: 'frankly', translation: '坦白地', level: 'CET6' },
  'fraud': { word: 'fraud', translation: '欺诈;骗子', level: 'CET6' },
  'freight': { word: 'freight', translation: '货物;货运', level: 'CET6' },
  'frequency': { word: 'frequency', translation: '频率;频繁', level: 'CET6' },
  'friction': { word: 'friction', translation: '摩擦;冲突', level: 'CET6' },
  'frontier': { word: 'frontier', translation: '边境;前沿', level: 'CET6' },
  'frustrate': { word: 'frustrate', translation: '挫败;使沮丧', level: 'CET6' },
  'fuel': { word: 'fuel', translation: '燃料;刺激', level: 'CET6' },
  'fulfill': { word: 'fulfill', translation: '履行;实现', level: 'CET6' },
  'function': { word: 'function', translation: '功能;函数', level: 'CET6' },
  'fund': { word: 'fund', translation: '基金;资金', level: 'CET6' },
  'fundamental': { word: 'fundamental', translation: '基本的;根本的', level: 'CET6' },
  'furnish': { word: 'furnish', translation: '提供;装备', level: 'CET6' },
  'furthermore': { word: 'furthermore', translation: '此外;而且', level: 'CET6' },
  'fusion': { word: 'fusion', translation: '融合;聚变', level: 'CET6+' },
  
  // G-Z (部分示例)
  'galaxy': { word: 'galaxy', translation: '星系;银河', level: 'CET6' },
  'gallery': { word: 'gallery', translation: '画廊;美术馆', level: 'CET6' },
  'gender': { word: 'gender', translation: '性别', level: 'CET6' },
  'generate': { word: 'generate', translation: '产生;生成', level: 'CET6' },
  'generous': { word: 'generous', translation: '慷慨的;大方的', level: 'CET6' },
  'genetic': { word: 'genetic', translation: '遗传的;基因的', level: 'CET6' },
  'genius': { word: 'genius', translation: '天才', level: 'CET6' },
  'genuine': { word: 'genuine', translation: '真正的;真诚的', level: 'CET6' },
  'geography': { word: 'geography', translation: '地理', level: 'CET6' },
  'geology': { word: 'geology', translation: '地质学', level: 'CET6' },
  'geometry': { word: 'geometry', translation: '几何学', level: 'CET6' },
  'gesture': { word: 'gesture', translation: '姿势;手势', level: 'CET6' },
  'gigantic': { word: 'gigantic', translation: '巨大的', level: 'CET6' },
  'glimpse': { word: 'glimpse', translation: '一瞥', level: 'CET6' },
  'global': { word: 'global', translation: '全球的', level: 'CET6' },
  'glorious': { word: 'glorious', translation: '光荣的;壮丽的', level: 'CET6' },
  'gossip': { word: 'gossip', translation: '闲话;流言', level: 'CET6' },
  'govern': { word: 'govern', translation: '统治;管理', level: 'CET6' },
  'grace': { word: 'grace', translation: '优雅;恩典', level: 'CET6' },
  'gracious': { word: 'gracious', translation: '亲切的;优雅的', level: 'CET6' },
  'gradual': { word: 'gradual', translation: '逐渐的', level: 'CET6' },
  'grant': { word: 'grant', translation: '授予;拨款', level: 'CET6' },
  'gravity': { word: 'gravity', translation: '重力;严重性', level: 'CET6' },
  'grease': { word: 'grease', translation: '油脂;润滑', level: 'CET6' },
  'greenhouse': { word: 'greenhouse', translation: '温室', level: 'CET6' },
  'grieve': { word: 'grieve', translation: '悲伤;使悲痛', level: 'CET6' },
  'grim': { word: 'grim', translation: '严酷的;冷酷的', level: 'CET6' },
  'grind': { word: 'grind', translation: '磨碎;折磨', level: 'CET6' },
  'grip': { word: 'grip', translation: '紧握;控制', level: 'CET6' },
  'groan': { word: 'groan', translation: '呻吟', level: 'CET6' },
  'gross': { word: 'gross', translation: '总的;粗俗的', level: 'CET6' },
  'guarantee': { word: 'guarantee', translation: '保证;担保', level: 'CET6' },
  'guardian': { word: 'guardian', translation: '监护人;守护者', level: 'CET6' },
  'guild': { word: 'guild', translation: '行会;协会', level: 'CET6+' },
  'guilty': { word: 'guilty', translation: '有罪的;内疚的', level: 'CET6' },
  
  // ... 更多词汇可以继续添加
};

// 提取文本中的高级词汇
export function extractAdvancedVocabulary(text: string): VocabularyItem[] {
  // 将文本分词
  const words = text.toLowerCase().match(/\b[a-z]+\b/g) || [];
  
  // 去重并查找高级词汇
  const uniqueWords = Array.from(new Set(words));
  const found: VocabularyItem[] = [];
  const added = new Set<string>();
  
  uniqueWords.forEach(word => {
    if (advancedVocabulary[word] && !added.has(word)) {
      found.push(advancedVocabulary[word]);
      added.add(word);
    }
  });
  
  // 按字母顺序排序
  return found.sort((a, b) => a.word.localeCompare(b.word));
}

// 高亮文本中的高级词汇
export function highlightAdvancedWords(text: string): Array<{ text: string; isAdvanced: boolean; vocab?: VocabularyItem }> {
  const words = text.match(/\b[a-z]+\b|\s+|[^\w\s]/gi) || [];
  
  return words.map(word => {
    const lowerWord = word.toLowerCase();
    const vocab = advancedVocabulary[lowerWord];
    
    return {
      text: word,
      isAdvanced: !!vocab,
      vocab
    };
  });
}

